# Generated by Django 5.1.4 on 2024-12-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0006_alter_cart_unique_together_cart_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='address',
            field=models.CharField(default='1234 ABC Street 40912 MI', max_length=100),
            preserve_default=False,
        ),
    ]
